---
title: 'Country Case Study: India and China'
output: html_document
date: "2024-01-18"
---

```{r, include=FALSE}
library(tidyverse)
library(sf)
library(leaflet)

sat <- read_csv("sat.csv")
facs <- read_csv("facilities.csv")[-1]
fac_caps_no_unknown <- read_csv("fac_caps_no_unknown.csv")[-1]
fac_caps_with_unknown <- read_csv("fac_caps_with_unknown.csv")[-1]
```

# Case Study: China

filter per-facility vistation

```{r, facility_visits}
fac_caps <- fac_caps_no_unknown %>%
  mutate(`Abbreviated Mission` = substr(Mission,1,4))

capture_counts <- fac_caps %>% 
  mutate(res = ifelse(`Camera Resolution` %in% c("Stereo High", "Vertical High", "2 to 4 feet"), "high", "low")) %>%
  filter(country %in% c("India", "China")) %>%
  group_by(facility_name, `Acquisition Date`, `Abbreviated Mission`, res, country, start_date) %>%
  summarise(days_visited = 1, n_caps = n()) 
  # summarise(n_caps = n()) 

totals <- capture_counts %>%
  ungroup() %>%
  group_by(facility_name, res, country) %>%
  summarise(n_caps = sum(n_caps), days_visited = sum(days_visited)) %>%
  pivot_wider(id_cols = c(facility_name, country), 
              names_from = res, 
              values_from = c(days_visited, n_caps),
              values_fill = 0)

totals <- totals %>%
  arrange(-days_visited_high)

colnames(totals) <- c("Facility", "Country", "# of Days Photographed (high res)", "# of Days Photographed (low res)", "# of Photos Taken (high res)", "# of Photos Taken (low res)")

totals <- totals[, c(1, 2, 3, 4)]

print(totals, n = nrow(totals))
```

```{r}
# Reshape data for ggplot2
totals_long <- totals %>%
  select(-c(n_caps_high, n_caps_low)) %>%
  pivot_longer(cols = c(days_visited_high, days_visited_low),
               names_to = c("res"))

# Create stacked bar chart
ggplot(totals_long, aes(x = facility_name, y = value, fill = res)) +
  geom_bar(stat = "identity") +
  labs(title = "Stacked Bar Chart",
       x = "facility",
       y = "days visited") +
  theme_minimal()
```


for each facility:
- make a table/plot of yearly visitation, distinguishing between high- and low-rez
- make a table w metadata of photos of the facilities. If you hover over a facility, its footprint shows up on the map next to it. If you click a link you can see the image. 

```{r}
fac_name <- "China Institute of Atomic Energy (Diffusion Lab)"

yearly_counts <- capture_counts %>%
  mutate(`Year` = as.numeric(substr(`Acquisition Date`,1,4))) %>%
  group_by(facility_name, Year) %>%
  summarise(n_caps = sum(n_caps)) %>%
  ungroup()

yearly_counts %>% 
  filter(facility_name == fac_name) %>%
  ggplot(aes(x = Year, y = n_caps, group = 1)) +
  geom_line()
```




```{r}
# missing <- setdiff(unique(fac_caps_no_unknown$facility_name), unique(capture_counts$facility_name))
# missing_df <- data.frame(facility_name = missing, n_caps = numeric(length(missing)))
# 
# totals <- rbind(totals, missing_df)
```

