---
title: "CORONA"
output: html_document
date: "2023-09-13"
---

## This document is deprecated as of 10/16/23. Awaiting removal.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(shiny)
library(shinyjs)
library(leaflet)
library(leaflet.extras2)
library(geojsonsf)
library(sf) # to make Simple Feature collections for leaflet timeslider
```

```{r}
fac_geodf <- read_csv("fac_geodf.csv")[-1]
captures <- read_csv("captures.csv")[-1]

fac_geodf$start_date[fac_geodf$start_date == -99] <- NA # unknown start dates
fac_geodf$start_date <- as.Date(paste(fac_geodf$start_date, "-01-01 00:00:00", sep = "")) # convert start date to Date object
captures$start_date <- as.Date(paste(captures$start_date, "-01-01", sep = "")) # convert start date to Date object -- not necessary, already knows

# filter the dataset to remove cases where the photo was taken before construction started
captures <- captures %>% filter(start_date <= Acquisitio)

# get date range
min_date = min(fac_geodf$start_date, na.rm = TRUE)
max_date = max(fac_geodf$start_date, na.rm = TRUE)
```

```{r}
# build coverage DF
coverage <- data.frame(year = integer(),
                       num_extant_facilities = integer(),
                       num_spotted_facilities = integer(),
                       coverage = double())

for (year in as.integer(format(min_date, "%Y")):as.integer(format(max_date, "%Y"))) {
  year_date <- as.Date(paste(year, "-01-01", sep = ""))
  
  # extant facilities
  fac_exist <- fac_geodf %>% 
    filter(start_date <= year_date) %>% 
    distinct(original_facility_name)  # Get unique facility names
  
  n_fac_exist <- nrow(fac_exist)
  
  # spotted facilities
  fac_spotted <- captures %>% 
    filter(Acquisitio <= year_date) %>% 
    distinct(original_facility_name)  # Get unique facility names
  
  n_fac_spotted <- nrow(fac_spotted)
  
  coverage <- bind_rows(coverage, data.frame(year = year,
                                             num_extant_facilities = n_fac_exist,
                                             num_spotted_facilities = n_fac_spotted,
                                             coverage = n_fac_spotted / n_fac_exist))
}

ggplot(coverage, aes(x = year)) +
  geom_ribbon(aes(ymin = 0, ymax = num_extant_facilities, fill = "Extant Facilities"), alpha = 0.75) +
  geom_ribbon(aes(ymin = 0, ymax = num_spotted_facilities, fill = "Spotted Facilities"), alpha = 0.75) +
  scale_fill_manual(values = c("Extant Facilities" = "#7eb0d5", "Spotted Facilities" = "#fd7f6f")) +
  labs(y = "Coverage", 
       x = "Year",
       fill = "") +
  theme_minimal()
```


```{r}
## CLIENT
ui <- fluidPage(
  tags$style(type = "text/css", "
      .js-irs-0 .irs-single, .js-irs-0 .irs-bar-edge, .js-irs-0 .irs-bar { }
      .js-irs-1 .irs-single, .js-irs-1 .irs-bar-edge, .js-irs-1 .irs-bar, .js-irs-1 .irs-from, .js-irs-1 .irs-to {background: red;
                                                  border-top: 1px solid red ;
                                                  border-bottom: 1px solid red ;}
      "),
  titlePanel("Coverage of Nuclear Facilities by the CORONA Recon Satellite Program"),
  sidebarLayout(
    sidebarPanel(
      checkboxInput("showUnknown","Show Facilities with Unknown Start Dates", value = FALSE),
      checkboxInput("showCaptures","Show Spotted Facilities", value = FALSE),
      sliderInput("dateSlider", "Adjust Date:", 
                  min = min_date, 
                  max = max_date, 
                  value = min_date, 
                  step = 49,
                  animate = animationOptions(interval = 250))
    ),
    mainPanel(
      leafletOutput("map", height = "600px", width = "800px"),
      plotOutput("plot")
    )
  )
)



## SERVER

server <- function(input, output, session) {
  state <- reactiveValues(fac = fac_geodf)
  
  # handle unknown dates
  adjust_nas <- function() {
    state$fac <- fac_geodf
    
    if(input$showUnknown) {
      state$fac$start_date <- replace(state$fac$start_date, is.na(state$fac$start_date), min_date) # replace NA values with the min slider date
    } else {
      state$fac <- state$fac %>% filter(!is.na(start_date)) #filter them out
    }
  }
  
  # filter by date range shown on slider
  fac_filtered_by_dates <- function() {
    state$fac[state$fac$start_date <= input$dateSlider,]
  }
  
  # filter for facilities which have been captured bf date
  captured_facs <- function() {
    captures %>% filter(Acquisitio <= input$dateSlider) %>% # filter for captures bf current date
      filter(original_facility_name %in% state$fac$original_facility_name) %>% # filter facs which aren't in current state (e.g. NA)
      group_by(fac_index) %>% # group by facility
      filter(Acquisitio == max(Acquisitio)) %>% # keep the most recent captures
      distinct(fac_index, .keep_all = TRUE) # make sure only one capture of each facility is present.
  }
  
  # add markers where there should be markers
  create_markers <- function() {
    leafletProxy(mapId = 'map') %>%
      clearMarkers() %>%
      addCircleMarkers(data = fac_filtered_by_dates(),
        lng = ~Longitude, lat = ~Latitude,
        radius = 5,
        weight = 1,
        color = "blue",
        opacity = 1,
        fillOpacity = 0.5,
        popup = ~paste("Name: ", original_facility_name, "<br>",
                   "Facility Start Date: ", start_date,
                   ifelse(input$showCaptures, "<br>Not Yet Photographed", "")),
      )
    
    if (input$showCaptures) {
      leafletProxy(mapId = 'map') %>%
      addCircleMarkers(data = captured_facs(),
        lng = ~Longitude, lat = ~Latitude,
        radius = 5,
        weight = 1,
        color = "red",
        opacity = 1,
        fillOpacity = 0.7,
        popup = ~paste("Name: ", original_facility_name, "<br>",
                   "Facility Start Date: ", start_date, "<br>",
                   "Most Recently Photographed: ", Acquisitio),
      )
    }
  }
   
  # run on startup. Adjust NAs and filter by date
  output$map <- renderLeaflet({
    map <- leaflet(leafletOptions( minZoom = 0 )) %>%
      addTiles() %>%
      setView(lng = 0,
              lat = 0,
              zoom = 1)
    map
  })
  
  # re-create map whenever date slider is changed
  observeEvent(eventExpr = { input$dateSlider }, handlerExpr = {
    adjust_nas()
    create_markers()
  })
  
  # re-create map when showUnkown checkbox is toggled
  observeEvent(eventExpr = { input$showUnknown }, handlerExpr = {
    adjust_nas()
    create_markers()
  })
  
  # re-create map when showUnkown checkbox is toggled
  observeEvent(eventExpr = { input$showCaptures }, handlerExpr = {
    adjust_nas()
    create_markers()
  })
}

shinyApp(ui, server)
```





```{r}
# scratch:

# create_plot <- function() {
  #   # create coverage table based on captures & facilities DFs
  #   
  #   output$plot <- renderPlot({ 
  #     coverage %>% ggplot(aes(x = year)) +
  #       geom_ribbon(aes(ymin = 0, ymax = num_extant_facilities, fill = "Extant Facilities"), alpha = 0.75) +
  #       geom_ribbon(aes(ymin = 0, ymax = num_spotted_facilities, fill = "Spotted Facilities"), alpha = 0.75) +
  #       scale_fill_manual(values = c("Extant Facilities" = "#7eb0d5", "Spotted Facilities" = "#fd7f6f")) +
  #       labs(y = "Coverage") +
  #       theme_minimal()
  #   })
  #   
  # }
```


## ------------ RANGE SLIDER VERSION --------------- ##

```{r}
min_date = min(fac_geodf$start_date, na.rm = TRUE)
max_date = max(fac_geodf$start_date, na.rm = TRUE)

ui <- fluidPage(
  tags$style(type = "text/css", "
      .js-irs-0 .irs-single, .js-irs-0 .irs-bar-edge, .js-irs-0 .irs-bar { }
      .js-irs-1 .irs-single, .js-irs-1 .irs-bar-edge, .js-irs-1 .irs-bar, .js-irs-1 .irs-from, .js-irs-1 .irs-to {background: red;
                                                  border-top: 1px solid red ;
                                                  border-bottom: 1px solid red ;}
      "),
  titlePanel("Map with Time Slider"),
  sidebarLayout(
    sidebarPanel(
      checkboxInput("showUnknown","Show Facilities with Unknown Start Dates?", value = FALSE),
      checkboxInput("showCaptures","Turn Facilities Red when Their Coordinates Have Been Photographed?", value = FALSE),
      sliderInput("dateSlider", "Show Facilities Where Construction Was Started Between the Dates:", 
                  min = min_date, 
                  max = max_date, 
                  value = c(min_date,min_date), 
                  step = 49,
                  dragRange =  TRUE, 
                  animate = animationOptions(interval = 250)),
      sliderInput("dateSliderCapture", "Show Facilities Which Were Photographed Between the Dates:", 
                  min = min_date, 
                  max = min_date, 
                  value = c(min_date,min_date), dragRange =  TRUE)
    ),
    mainPanel(
      leafletOutput("map", height = "600px", width = "900px")
    )
  )
)

# add capture range slider, show captures checkbox

# when "Show captures" checkbox is on:
#   if a facility on the map (present in fac_filtered_by_dates) has a capture that occurred within the specified range of dates, turn the facility red

server <- function(input, output, session) {
  state <- reactiveValues(fac = fac_geodf)
  
  # handle unknown dates
  adjust_nas <- function() {
    state$fac <- fac_geodf
    
    if(input$showUnknown) {
      state$fac$start_date <- replace(state$fac$start_date, is.na(state$fac$start_date), input$dateSlider[1]) # replace NA values with the lowest date on slider
    } else {
      state$fac <- state$fac %>% filter(!is.na(start_date)) #filter them out
    }
  }
  
  # filter by date range shown on slider
  fac_filtered_by_dates <- function() {
    state$fac[state$fac$start_date >= input$dateSlider[1] & state$fac$start_date <= input$dateSlider[2], ]
  }
  
  # create a map with facilities filtered by date
  create_map <- function() {
    leaflet() %>%
      addTiles() %>%
      addCircleMarkers(data = fac_filtered_by_dates(),
        lng = ~Longitude, lat = ~Latitude,
        radius = 5,
        weight = 1,
        color = "blue",
        opacity = 1,
        fillOpacity = 0.5
      )
  }
  
  # run on startup. Adjust NAs and filter by date
  output$map <- renderLeaflet({
    map <- leaflet(leafletOptions( minZoom = 0 )) %>%
      addTiles() %>%
      setView(lng = 0,
              lat = 0,
              zoom = 1)
    map
  })
  
  # re-create map whenever date slider is changed
  observeEvent(eventExpr = { input$dateSlider }, handlerExpr = {
    adjust_nas()
    
    leafletProxy(mapId = 'map') %>%
      clearMarkers() %>%
      addCircleMarkers(data = fac_filtered_by_dates(),
        lng = ~Longitude, lat = ~Latitude,
        radius = 5,
        weight = 1,
        color = "blue",
        opacity = 1,
        fillOpacity = 0.5
      )
  })
  
  # # re-create map whenever date slider is changed
  # observeEvent(eventExpr = { input$dateSlider }, handlerExpr = {
  #   output$map <- renderLeaflet({
  #     map <- create_map()
  #     map
  #   })
  # })
  
  # # re-create map whenever date slider is changed
  # observeEvent(eventExpr = { input$dateSlider }, handlerExpr = {
  #   output$map <- output$map %>% addCircleMarkers(data = fac_filtered_by_dates(),
  #       lng = ~Longitude, lat = ~Latitude,
  #       radius = 5,
  #       weight = 1,
  #       color = "blue",
  #       opacity = 1,
  #       fillOpacity = 0.5
  #     )
  # })
  
  # re-create map when showUnkown checkbox is toggled
  observeEvent(eventExpr = { input$showUnknown }, handlerExpr = {
    adjust_nas()
    
    leafletProxy(mapId = 'map') %>%
      clearMarkers() %>%
      addCircleMarkers(data = fac_filtered_by_dates(),
        lng = ~Longitude, lat = ~Latitude,
        radius = 5,
        weight = 1,
        color = "blue",
        opacity = 1,
        fillOpacity = 0.5
      )
  })
  
  # observeEvent(eventExpr = { input$showCaptures }, handlerExpr = {
  #   map <- addCircleMarkers()
  # })
  # 
  # function to animate map. Currently on hold.
  # observeEvent(eventExpr = { input$runMap }, handlerExpr = {
  #   auto_play <- reactiveTimer(1000000)  # Adjust the interval (in milliseconds) as needed
  #   
  #   observe({
  #     auto_play()
  #     
  #     start_date <- input$dateSlider[1]
  #     current_value <- input$dateSlider[2]
  #     max_date <- max(fac_geodf$start_date, na.rm = TRUE)
  #     
  #     if (current_value < max_date) {
  #       updateSliderInput(session, "dateSlider", value = c(start_date, current_value + 365))
  #     } 
  #     # else {
  #       # updateSliderInput(session, "dateSlider", value = c(start_date, 1))
  #     # }
  #   })
  # })
}

shinyApp(ui, server)
```

```{r}
# fac_geodf$time <- as.Date(paste(fac_geodf$start_date, "-01-01 00:00:00", sep = "")) # convert start date to Date column
# fac_geodf$time[is.na(fac_geodf$time)] <- as.Date("1900-01-01") # assume unknown start dates were built in 1900
# 
# fac_geodf$time <- as.numeric(1000*difftime(as.POSIXct(fac_geodf$time), as.POSIXct("1970-01-01"), units = "secs"))

# replace geometry column with character formatted "POINT (Longitude Latitude)"
# fac_geodf$geometry <- paste("POINT (", fac_geodf$Longitude, " ", fac_geodf$Latitude, ")", sep = "")

# fac_sf <- st_as_sf(x = fac_geodf,                        
#           coords = c("Latitude", "Longitude"),
#           wkt = "geometry")
```

