---
title: "CORONA"
output: html_document
date: "2023-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(shiny)
library(shinyjs)
library(leaflet)
```

# load data
```{r, include=FALSE}
facs <- read_csv("facilities.csv")[-1]
missiles <- read_csv("missiles.csv")[-1]
fac_caps_orig <- read_csv("fac_captures.csv")[-1]
miss_caps_orig <- read_csv("miss_captures.csv")[-1]

# get date range
min_date = min(append(facs$start_date, missiles$start_date), na.rm = TRUE)
max_date = max(append(facs$start_date, missiles$start_date), na.rm = TRUE)
```

## Calculate and Plot Facility Coverage
```{r}
fac_caps <- fac_caps_orig

# Build coverage DF
coverage <- data.frame(year = integer(),
                       num_extant_facilities = integer(),
                       num_spotted_facilities = integer(),
                       coverage = double())

spotted <- c()

for (year in as.integer(format(min_date, "%Y")):as.integer(format(max_date, "%Y"))) {
  year_date <- as.Date(paste(year, "-01-01", sep = ""))
  
  # extant facilities
  fac_exist <- facs %>%
    filter(start_date <= year_date) %>%
    distinct(facility_name)  # Get unique facility names
  
  n_fac_exist <- nrow(fac_exist)
  
  # spotted facilities
  fac_spotted <- fac_caps %>%
    filter(Acquisitio <= year_date) %>%
    distinct(facility_name)  # Get unique facility names
  
  spotted <- unique(append(spotted,fac_spotted$facility_name))
  
  fac_caps <- fac_caps %>% 
    filter(Acquisitio > year_date)
  
  n_fac_spotted <- length(spotted)
  
  coverage <- bind_rows(coverage, data.frame(year = year,
                                             num_extant_facilities = n_fac_exist,
                                             num_spotted_facilities = n_fac_spotted,
                                             coverage = n_fac_spotted / n_fac_exist))
}

## Plot
ggplot(coverage, aes(x = year)) +
  geom_ribbon(aes(ymin = 0, ymax = num_extant_facilities, fill = "Extant Facilities"), alpha = 0.75) +
  geom_ribbon(aes(ymin = 0, ymax = num_spotted_facilities, fill = "Spotted Facilities"), alpha = 0.75) +
  scale_fill_manual(values = c("Extant Facilities" = "#7eb0d5", "Spotted Facilities" = "#fd7f6f")) +
  labs(y = "Coverage", 
       x = "Year",
       fill = "") +
  theme_minimal()
```

## Calculate and Plot Missile Coverage
```{r}
miss_caps <- miss_caps_orig

# Build coverage DF
coverage <- data.frame(year = integer(),
                       num_extant_facilities = integer(),
                       num_spotted_facilities = integer(),
                       coverage = double())

spotted <- c()

for (year in as.integer(format(min_date, "%Y")):as.integer(format(max_date, "%Y"))) {
  year_date <- as.Date(paste(year, "-01-01", sep = ""))
  
  # extant facilities
  miss_exist <- missiles %>%
    filter(start_date <= year_date) %>%
    distinct(address_found)  # Get unique facility names
  
  n_miss_exist <- nrow(miss_exist)
  
  # spotted missiles
  miss_spotted <- miss_caps %>%
    filter(Acquisitio <= year_date) %>%
    distinct(address_found)  # Get unique missile names
  
  spotted <- unique(append(spotted,miss_spotted$address_found))
  
  miss_caps <- miss_caps %>% 
    filter(Acquisitio > year_date)
  
  n_miss_spotted <- length(spotted)
  
  coverage <- bind_rows(coverage, data.frame(year = year,
                                             num_extant_missiles = n_miss_exist,
                                             num_spotted_missiles = n_miss_spotted,
                                             coverage = n_miss_spotted / n_miss_exist))
}

## Plot
ggplot(coverage, aes(x = year)) +
  geom_ribbon(aes(ymin = 0, ymax = num_extant_missiles, fill = "Extant missiles"), alpha = 0.75) +
  geom_ribbon(aes(ymin = 0, ymax = num_spotted_missiles, fill = "Spotted missiles"), alpha = 0.75) +
  scale_fill_manual(values = c("Extant missiles" = "#7eb0d5", "Spotted missiles" = "#fd7f6f")) +
  labs(y = "Coverage", 
       x = "Year",
       fill = "") +
  theme_minimal()
```