---
title: "Data Prerocessing"
output: html_document
date: "2023-09-25"
---

```{r}
library(xlsx)
library(tidyverse)
library(sf)
```


# Scripts to clean up the original datasets supplied by Quido

## clean up facilities dataset
```{r}
# load original data
facs <- read.xlsx("NL_geocoded_working.xlsx",1)

# cleanup 
facs <- facs %>% select(-NA.) # remove random column
colnames(facs) <- c("country", "country_code", "facility_name", "coordinates", "start_date") # rename columns

facs <- facs %>%
  mutate(coordinates = gsub(",", ".", coordinates)) %>% # fix inconsistency in coords
  filter(!is.na(coordinates)) # remove rows with no coords (why do these exist?)

facs$start_date[facs$start_date == -99] <- NA # replace -99 (unknown start dates) with NA
facs$start_date <- as.Date(paste(facs$start_date, "-01-01 00:00:00", sep = "")) # convert start date to Date object

# add lat and lng cols
facs <- facs %>% 
  mutate(lat = as.character(lapply(strsplit(coordinates, "[.]"), function(x) paste(x[1], x[2], sep = "."))),
         lng = as.character(lapply(strsplit(coordinates, "[.]"), function(x) paste(x[3], x[4], sep = "."))))

facs <- facs[, c("facility_name", "country", "country_code", "coordinates", "lat", "lng", "start_date")] # reorder columns

write.csv(facs, "facilities.csv")
```

## clean up missiles dataset
```{r}
# load original data
missiles <- read.xlsx("Missiles_datageocoding_prep.xlsx", 1)

# cleanup
colnames(missiles) <- c("address", "country", "coordinates", "address_found", "No.rd.", "W.h", "start_date","end_date","armament","RA_or_enclosure" ) # rename columns

missiles <- missiles %>%
  mutate(coordinates = gsub(",", ".", coordinates)) # fix inconsistency in coords

missiles$start_date <- as.Date(paste(missiles$start_date, "-01-01 00:00:00", sep = "")) # convert start date to Date object
missiles$end_date <- as.Date(paste(missiles$end_date, "-01-01 00:00:00", sep = ""))

missiles$coordinates[27] <- paste(missiles$coordinates[27],".0",sep = "") # add '.0' at the end of the 27th coord cuz it was misformatted

# add lat and lng cols
missiles <- missiles %>% 
            mutate(lat = as.character(lapply(strsplit(coordinates, "[.]"), function(x) paste(x[1], x[2], sep = "."))),
                   lng = as.character(lapply(strsplit(coordinates, "[.]"), function(x) paste(x[3], x[4], sep = "."))))

missiles <- missiles[, c("address_found", "country", "coordinates", "lat", "lng", "start_date", "end_date", "address","No.rd.", "W.h","armament","RA_or_enclosure")] # reorder columns

write.csv(missiles, "missiles.csv")
```


## clean up and integrate sat datasets
```{r}
# need to clean up coords n shit
sat1 <- read_csv("sat1.csv")
sat2 <- read_csv("sat2.csv")
sat3 <- read_csv("sat3.csv")

# fix column inconsistencies
setdiff(colnames(sat2), colnames(sat1))
sat1$`Segment Count` <- rep(NA, nrow(sat1))
sat1$`Operations Number` <- rep(NA, nrow(sat1))
colnames(sat1)[colnames(sat1) == "NW Cormer Lat dec"] <- "NW Corner Lat dec"
sat1$`Data Source` <- rep("declass1", nrow(sat1))

setdiff(colnames(sat1), colnames(sat2))
sat2$`Direction Flag` <- rep(NA, nrow(sat2))
sat2$`Data Source` <- rep("declass2", nrow(sat2))

# reformat Display ID for sat1, sat2 due to bad formatting in CSV provided by USGS
reformat_id <- function(id, n) {
  id <- strsplit(id, ",")[[1]][1] # split by comma, take first item
  id
  # this code inserted a "-", but I don't think that is actually necessary:
  # # after the right n of characters insert "-"
  # new_id <- paste(substr(id, 1, n), "-", substr(id, n+1, nchar(id)), sep = "")
  # new_id
}

sat1$`Display ID` <- lapply(sat1$`Display ID`, reformat_id, n = 6)
sat2$`Display ID` <- lapply(sat2$`Display ID`, reformat_id, n = 7)

sat1_2 <- rbind(sat1,sat2)

setdiff(colnames(sat1_2), colnames(sat3))
sat3 <- sat3 %>% 
  mutate(`Camera Type` = str_replace(Camera, "A", "High Resolution Surveillance Camera - Aft")) %>%
  mutate(`Camera Type` = str_replace(`Camera Type`, "F", "High Resolution Surveillance Camera - Forward")) %>%
  mutate(`Camera Type` = str_replace(`Camera Type`, "T", "Lower Resolution Terrain Mapping Camera")) %>%
  select(-Camera)

colnames(sat1_2)[colnames(sat1_2) == "Frame"] <- "Frame Number"
colnames(sat1_2)[colnames(sat1) == "Down Load Available"] <- "Download Available"
sat3$`Direction Flag` <- rep(NA, nrow(sat3))
sat3$`Segment Count` <- rep(NA, nrow(sat3))
sat3$`Data Source` <- rep("declass3", nrow(sat3))

sat <- rbind(sat1_2, sat3)
```

```{r}
# make wkt representation of sat geometry
sat <- sat %>% 
  mutate(geometry = paste("POLYGON ((", 
                          `NW Corner Long dec`, " ", `NW Corner Lat dec`, ",", 
                          `NE Corner Long dec`, " ", `NE Corner Lat dec`, ",",
                          `SE Corner Long dec`, " ", `SE Corner Lat dec`, ",",
                          `SW Corner Long dec`, " ", `SW Corner Lat dec`, ",", 
                          `NW Corner Long dec`, " ", `NW Corner Lat dec`, "))", sep = ""))

sat <- sat[, -c(13:32)]

sat$`Display ID` <- as.character(sat$`Display ID`)

write_csv(sat, "sat.csv")
```


## clean up captures dataset (this code is deprecated)
```{r}
captures <- read_csv("captures.csv")[-1]

# rename imptnt cols
colnames(captures)[2] <- "country"
colnames(captures)[3] <- "country_code"
colnames(captures)[4] <- "facility_name"
colnames(captures)[5] <- "coordinates"
colnames(captures)[7] <- "lat"
colnames(captures)[8] <- "lng"

captures$start_date[captures$start_date == -99] <- NA # replace -99 (unknown start dates) with NA
captures$start_date <- as.Date(paste(captures$start_date, "-01-01 00:00:00", sep = "")) # convert start date to Date object

write.csv(captures, "captures.csv")
```

